#!/usr/bin/env python3

# Created by: Adam Diwani
# Created on: December 22, 2020
# This program prints all numbers from 1000-2000 in a for loop


def main():
    #function prints all numbers from 1000-2000
    
    loop_counter = 1000
    
    print("All numbers that range from 1000-2000 are: ")
    
    for loop_counter in range(1000, 2001):
        print (loop_counter, end = " ")
        if loop_counter % 5 == 4:
            print(" ")
            

if __name__ == "__main__":
    main()
